# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = gcc
OBJDUMP = objdump
STRIP = strip
LDFLAGS =  -lSDL2  -lpng16 -lz

# Package name and version number:

PROGRAM_PREFIX = chocolate-
PACKAGE = chocolate-doom
PACKAGE_NAME = Chocolate Doom
PACKAGE_STRING = Chocolate Doom 3.0.1
PACKAGE_TARNAME = chocolate-doom
PACKAGE_VERSION = 3.0.1

# Documentation files to distribute with packages.

DOC_FILES = README.md        \
            README.Music.md  \
            COPYING          \
            NEWS.md

